---
path: ../
memory: 1G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  FEC_API_WHITELIST_IPS: true
  APP_NAME: fec | api | stage
  PRODUCTION: True
  WEB_CONCURRENCY: 4
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-stage
  - fec-s3-stage
applications:
  - name: celery-worker
    instances: 1
    memory: 1G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel ${LOGLEVEL:=INFO} --concurrency 2
